#!/bin/bash

# test for dependencies

if ! command -v xclip >/dev/null 2>&1;
then
	echo "Looking for xclip...MISSING.\nPlease install it and restart this installer.\n"
	exit;
fi

if ! command -v curl >/dev/null 2>&1;
then
	echo "Looking for curl...MISSING.\nPlease install it and restart this installer.\n"
	exit;
fi

sleep 2

# add icon
echo "Installing owncloud icon to your homedir (/home/$(whoami)/.icons)..."
if [ ! -d ~/.icons ]; then
  mkdir ~/.icons
fi
cp owncloud.png ~/.icons/

# place core bash script
echo "Installing sharing script to your homedir (/home/$(whoami)/bin)..."
if [ ! -d ~/bin ]; then
  mkdir ~/bin
fi
cp shareLinkCreator ~/bin
cp shareLinkCreator.config ~/bin
cp gkeyring.py ~/bin

## thunar specific
if [ -f /usr/bin/thunar ]
then
	grep -q 1413987903893246-3 ~/.config/Thunar/uca.xml
	if [ $? != 0 ]; then
		echo "Thunar installed, processing custom actions file..."
		# backup original thunar actions file
		cp ~/.config/Thunar/uca.xml ~/.config/Thunar/uca.xml.sharelinkBAK

		# replace last line "</actions>"
		sed -i '$d' ~/.config/Thunar/uca.xml
		cat shareLinkCreator.thunar_action >> ~/.config/Thunar/uca.xml
	fi
fi

## nemo specific
if [ -f /usr/bin/nemo ]
then
	echo "Nemo installed, copying custom action file..."
	cp shareLinkCreator.nemo.action ~/.local/share/nemo/actions/
fi
