#!/bin/bash
#
# Public Link Creator Version 1.0
#
# (c) Copyright 2013 Bjoern Schiessle <bjoern@schiessle.org>
#
# This program is free software released under the MIT License, for more details
# see LICENSE.txt or http://opensource.org/licenses/MIT
#
# Before you can use the program you need to adjust at least the "baseURL",
# "shareURL", "localDir" and "username" config parameters.
#
# Requirements:
#
# - curl
# - xclip
# - python-gnomekeyring

# load config parameters
. "$(dirname $0)/config"

notify() {
    notify-send "ownCloud" "$1" -i owncloud -t 3000
}

error() {
    notify "Error: $1"
    exit 1
}

if [ $# != 1 ]; then
    error "Please select one file"
elif [ ! -f "$1" ]; then
    error "File not found: $1"
fi

file=$1

if [ "${file##$localDir}" == "$file" ]; then
    error "Please select file from $localDir"
fi

file=$(echo "$1" | sed "s#^$(echo $localDir)##g")

webdavURL="$baseURL/remote.php/webdav"
url=$(echo "$webdavURL/$file" | sed 's/\ /%20/g')
shareAPI="$baseURL/ocs/v1.php/apps/files_sharing/api/v1/shares"

# create public link share, first parameter contains the path of the shared file/folder
createShare() {
    echo -n 'Getting a link from server... '
    result=$(curl -u "$username":"$password" --silent "$shareAPI" --connect-timeout 4 -d path="$1" -d shareType=3)
    if [ $? != 0 ]; then
        error "Cannot complete the request"
    fi
    echo $result | grep -q "<status>failure</status>"
    if [ $? == 0 ]; then
        error "File is not uploaded yet"
    else
        shareCode=$(echo $result | sed -e 's/.*<url>\(.*\)<\/url>.*/\1/')
        shareCode=$(echo $shareCode | sed 's/.*\&amp;t=//')
        shareLink=$(echo $shareURL$shareCode)
        echo -n $shareLink | xclip -sel clip
        echo 'done.'
    fi
}

if [ -z $username ]; then
    error "Please specify username in config file"
fi

password=$(python "$(dirname $0)/gkeyring.py" "$username:$baseURL/")

if [ -z $password ]; then
    error "Cannot found stored password"
fi

createShare "/$file"
notify "The link has been copied to clipboard"
